stages:
  [cleanup, test, deploy]

compile:
  stage: cleanup
  script:
    - fuser -k 5000/tcp || true

test:
  stage: test
  script:
    - echo "Testing"
    - pip install -r requirements.txt
    - python3 -m pytest
    - echo "Test completed"

deploy_heroku:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp26 --api-key=$HEROKU_API_KEY