# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  [cleanup, test, deploy]

compile:
  stage: cleanup
  script:
    - fuser -k 5000/tcp || true

test:
  stage: test
  script:
    - echo "Tesing"


deploy_VM:
  stage: deploy
  script:
    - touch
    - echo "Deploying."
    - export FLASK_APP=app
    - flask run | logs.txt &

  environment: 
    name: VM
    url: 146.169.43.142

deploy_heroku:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp26 --api-key=8704aac6-481f-41d0-bd73-7328268e327a